function fig_hdl = olfactometer_build
% OLFACTOMETER_BUILD
%-------------------------------------------------------------------------------
% File name   : olfactometer_build.m
% Generated on: 09-Sep-2011 05:03:28
% Description :
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figure1;

%% ---------------------------------------------------------------------------
    function build_gui()
        % Creation of all uicontrols
        
        % --- FIGURE -------------------------------------
        handles.figure1 = figure( ...
            'Tag', 'figure1', ...
            'Units', 'characters', ...
            'Position', [106.8 10.4615384615385 106.8 53.4615384615385], ...
            'Name', 'olfactometer', ...
            'MenuBar', 'None', ...
            'NumberTitle', 'off', ...
            'Color', get(0,'DefaultUicontrolBackgroundColor'));
        
        % --- MENU ---------------------------------------------
        handles.menuFile =  uimenu('Label','File');
        uimenu(handles.menuFile,'Label','Load odorset configuration...','Callback',@(hObject,eventdata)loadOdorSet(hObject,eventdata));
        uimenu(handles.menuFile,'Label','Save configuration','Callback','','Enable','Off');
        uimenu(handles.menuFile,'Label','Save configuration as...','Callback','','Enable','Off');
        
%         handles.menuConf =  uimenu('Label','Configurations');
%         uimenu(handles.menuConf,'Label','Set Configuration Path...','Callback','');
%         handles.ConfPath = uimenu(handles.menuConf,'Label','path','Callback','','Separator','on','Enable','Off');
%         %loop
%         uimenu(handles.menuConf,'Label','Loop through directory','Callback','','Separator','on');
%         %end loop
        
        %        @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject))
        
        % --- STATIC TEXTS -------------------------------------
        handles.title = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'title', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [-0.2 50.4615384615385 50.2 2.46153846153846], ...
            'FontSize', 14, ...
            'String', 'Olfactometer Control GUI');
        
        handles.lastCommandLabel = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'lastCommandLabel', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [55.5 47.1 20.6 1.07692307692308], ...
            'String', 'Last Command:');
        
        handles.lastCommand = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'lastCommand', ...
            'Enable', 'off', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [74 47.1 29.6 1.07692307692308], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'lastCommand');
        
        handles.lastResponseLabel = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'lastResponseLabel', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [55.5 45.1 20.6 1.07692307692308], ...
            'String', 'Last Response:');
        
        handles.lastResponse = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'lastResponse', ...
            'Enable', 'off', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [74 45.1 29.6 1.07692307692308], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'lastResponse');
                
        %% loop for the frame specifications
        labels={'Pre', 'Odor', 'Post', 'ISI'};
        
        handles.frameSpecificationLabels=zeros(1,4);
        handles.frameSpecificationFields=zeros(1,4);
        handles.frameSpecificationRealTimes=zeros(1,4);
        
        for i = 1:4
            horzOffset=(i-1)*20;
            handles.frameSpecificationLabels(i) = uicontrol( ...
                'Parent', handles.figure1, ...
                'Tag', ['frameSpecificationLabel_' num2str(i)], ...
                'Style', 'text', ...
                'Units', 'characters', ...
                'Position', [horzOffset+5.8 38.5 5.5 1.69230769230769], ...
                'HorizontalAlignment', 'left', ...
                'String', [labels{i} ':']);
            handles.frameSpecificationFields(i) = uicontrol( ...
                'Parent', handles.figure1, ...
                'Tag', ['frameSpecificationField_' num2str(i)], ...
                'Style', 'edit', ...
                'Units', 'characters', ...
                'Position', [horzOffset+11.3 38.8 5 1.69230769230769], ...
                'String', '', ...
                'BackgroundColor', [1 1 1], ...
                'Value', 1, ...
                'Callback', @(hObject,eventdata)olfactometer('frameNum_Callback',hObject,eventdata,guidata(hObject)));
            
            handles.frameSpecificationRealTimes(i) = uicontrol( ...
                'Parent', handles.figure1, ...
                'Tag', ['frameSpecificationRealTimes_' num2str(i)], ...
                'Style', 'text', ...
                'Units', 'characters', ...
                'HorizontalAlignment', 'left', ...
                'Position', [horzOffset+16.3 38.5 15 1.69230769230769], ...
                'String', '(5 secs)');
        end
        
        
        
        % --- CheckBoxes --------------------------------------
        handles.olfactometerEnable = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'enable', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', [5.8 44.6153846153846 12 1.69230769230769], ...
            'String', 'enable?', ...
            'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));
        
        
        handles.olfactometerRandomize = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'randomize', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', [5.8 42.85 18 1.69230769230769], ...
            'String', 'Randomize?', ...
            'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));
        
        % --- PUSHBUTTONS -------------------------------------
        handles.pushbutton1 = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'connect', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [32.2 46.6153846153846 23.6 1.69230769230769], ...
            'String', 'Connect / Reconnect', ...
            'Callback', @(hObject,eventdata)olfactometer('connect_Callback',hObject,eventdata,guidata(hObject)) );
        
         handles.RefreshButton = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'refresh', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [85.8 38.7 15.5 1.69230769230769], ...
            'String', 'Refresh', ...
            'Callback', @(hObject,eventdata)olfactometer_refresh);
        
        % --- EDIT TEXTS -------------------------------------
        handles.edit1 = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'host', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [5.8 46.6153846153846 25.8 1.69230769230769], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Olfactometer IP', ...
            'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));        
        
        % --- PANELS -------------------------------------
        handles.valvePanel = uibuttongroup( ...
            'Parent', handles.figure1, ...
            'Tag', 'valvePanel', ...
            'Units', 'characters', ...
            'Position', [5.2 1.92307692307692 98 35.0769230769231], ...
            'Title', 'Valve Settings',...
            'SelectionChangeFcn', @olfactometerValveChange);
        
        % headings
        
        handles.text6 = uicontrol( ...
            'Parent', handles.valvePanel, ...
            'Tag', 'valveHeading', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [2.2 31.7692307692308 7.4 1.38461538461538], ...
            'String', 'Valve');
        
        handles.text7 = uicontrol( ...
            'Parent', handles.valvePanel, ...
            'Tag', 'enableHeading', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [10.6 31.7692307692308 10.4 1.38461538461538], ...
            'String', 'enable?');
        
        handles.text8 = uicontrol( ...
            'Parent', handles.valvePanel, ...
            'Tag', 'odor1Heading', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [21.8 31.7692307692308 10.4 1.38461538461538], ...
            'String', 'Odor 1');
        
        handles.text9 = uicontrol( ...
            'Parent', handles.valvePanel, ...
            'Tag', 'odor2Heading', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [48.4000000000001 31.7692307692308 10.4 1.38461538461538], ...
            'String', 'Odor 2');
        
        
        %%% LOOOPPPPPPPPP
        
        handles.valveRadioButton = zeros(1,16);
        handles.valveEnable = zeros(1,16);
        handles.valveOdor1Name = zeros(1,16);
        handles.valveOdor1Prefix = zeros(1,16);
        handles.valveOdor1Dilution = zeros(1,16);
        handles.valveOdor2Name = zeros(1,16);
        handles.valveOdor2Prefix = zeros(1,16);
        handles.valveOdor2Dilution = zeros(1,16);
        handles.valveBank = zeros(1,16);
        
        for i = 1:16
            % 9 things x 16
            % drop second number in position by 2 each time.
            
            vertOffset = (i-1)*2;
            handles.valveRadioButton(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveRadioButton_' num2str(i)], ...
                'Style', 'radiobutton', ...
                'Units', 'characters', ...
                'Position', [3.2 30.0769230769231-vertOffset 8.2 1.76923076923077], ...
                'String', num2str(i), ...
                'Value', 0);
            
            handles.valveEnable(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveEnable_' num2str(i)], ...
                'Style', 'checkbox', ...
                'Units', 'characters', ...
                'Position', [12.6 30.0769230769231-vertOffset 4.4 1.76923076923077], ...
                'String', '', ...
                'Callback', @(hObject,eventdata)olfactometer('check_Callback',hObject,eventdata,guidata(hObject)));
    
            if (i == 1)
                set(handles.valveEnable(i),'Value',1)
            end
            
            %odor 1
            handles.valveOdor1Name(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveOdor1Name_' num2str(i)], ...
                'Style', 'edit', ...
                'Units', 'characters', ...
                'Position', [21.8 30.0769230769231-vertOffset 14.8 1.69230769230769], ...
                'BackgroundColor', [1 1 1], ...
                'String', '-', ...
                'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));
            handles.valveOdor1Prefix(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveOdor1Prefix_' num2str(i)], ...
                'Style', 'text', ...
                'Units', 'characters', ...
                'Position', [36.8 30.4769230769231-vertOffset 2.8 1.07692307692308], ...
                'String', '1:');
            handles.valveOdor1Dilution(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveOdor1Dilution_' num2str(i)], ...
                'Style', 'edit', ...
                'Units', 'characters', ...
                'Position', [40.2 30.0769230769231-vertOffset 6.2 1.69230769230769], ...
                'BackgroundColor', [1 1 1], ...
                'String', '10', ...
                'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));
                        
            %odor 2
            handles.valveOdor2Name(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveOdor2Name_' num2str(i)], ...
                'Style', 'edit', ...
                'Units', 'characters', ...
                'Position', [48.4000000000001 30.0769230769231-vertOffset 14.8 1.69230769230769], ...
                'BackgroundColor', [1 1 1], ...
                'String', '-', ...
                'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));
            handles.valveOdor2Prefix(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveOdor2Prefix_' num2str(i)], ...
                'Style', 'text', ...
                'Units', 'characters', ...
                'Position', [63.4 30.4769230769231-vertOffset 2.8 1.07692307692308], ...
                'String', '1:');
            handles.valveOdor2Dilution(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveOdor2Dilution_' num2str(i)], ...
                'Style', 'edit', ...
                'Units', 'characters', ...
                'Position', [66.8000000000001 30.0769230769231-vertOffset 6.2 1.69230769230769], ...
                'BackgroundColor', [1 1 1], ...
                'String', '-', ...
                'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)));
 
            
            % Bank
            
            handles.valveBank(i) = uicontrol( ...
                'Parent', handles.valvePanel, ...
                'Tag', ['valveBank_' num2str(i)], ...
                'Style', 'popupmenu', ...
                'Units', 'characters', ...
                'Position', [74.4 30.280230769231-vertOffset 19.8 1.53846153846154], ...
                'BackgroundColor', [1 1 1], ...
                'String', {'Bank 1','Bank 2','Bank 3','Bank 4'}, ...
                'Callback', @(hObject,eventdata)olfactometer('generic_Callback',hObject,eventdata,guidata(hObject)), ...
                'Value', 1);
            
%             disp([get(handles.valveEnable(i), 'Tag') '=0    Config 7 gh.olfactometer.' get(handles.valveEnable(i), 'Tag') ' Numberic 1'] )
%             disp([get(handles.valveOdor1Name(i), 'Tag') '=' get(handles.valveOdor1Name(i), 'String') '     Config 7 gh.olfactometer.' get(handles.valveOdor1Name(i), 'Tag') ' Numberic 0'] )
%             disp([get(handles.valveOdor1Dilution(i), 'Tag') '=' get(handles.valveOdor1Dilution(i), 'String') '     Config 7 gh.olfactometer.' get(handles.valveOdor1Dilution(i), 'Tag') ' Numberic 1 Min 1'] )
%             disp([get(handles.valveOdor2Name(i), 'Tag') '=' get(handles.valveOdor2Name(i), 'String') '     Config 7 gh.olfactometer.' get(handles.valveOdor2Name(i), 'Tag') ' Numberic 0'] )
%             disp([get(handles.valveOdor2Dilution(i), 'Tag') '=' get(handles.valveOdor2Dilution(i), 'String') '     Config 7 gh.olfactometer.' get(handles.valveOdor2Dilution(i), 'Tag') ' Numberic 1 Min 1'] )
%             disp([get(handles.valveBank(i), 'Tag') '=1     Config 7 gh.olfactometer.' get(handles.valveBank(i), 'Tag') ' Numberic 1 Min 1 Max 4'] )
%  
            
        end
    end

end
