@echo off

:CL
rem         ::: CL (MSVC) settings. :::
set QCAMMEX_ENG=CL

set QCAMMEX_MATLAB_PATH=C:\Program Files\MATLAB\R2007a

rem set QCAMMEX_VS_HOME=C:\Progra~1\Micros~2\VC
set QCAMMEX_VS_HOME=C:\Progra~1\Micros~2\VC

rem set QCAMMEX_WXWIDGETS_HOME=C:\wxWidgets-2.8.7

set QCAMMEX_MS_SDK=C:\Program Files\Microsoft SDKs\Windows\v6.1
rem set QCAMMEX_MS_SDK=C:\Program Files\Microsoft Platform SDK for Windows Server 2003 R2
set QCAMMEX_CL_BIN=%QCAMMEX_VS_HOME%\bin
set QCAMMEX_COMPILER=%QCAMMEX_CL_BIN%\cl
set QCAMMEX_LINKER=%QCAMMEX_CL_BIN%\link

rem set QCAMMEX_WXWIDGETS_PREPROCESSOR_ARGS=NDEBUG WIN32 _WINDOWS __WINDOWS__ __WXMSW__ __WIN95__ __WIN32__ WINVER=0x0400 STRICT
set QCAMMEX_COMPILER_ARGS_NON_MEX=/c /O2 /nologo -DQCAMMEX_LOCALTIME_DEPRECATED -DQCAMMEX_COMPILER_CL -DQCAMMEX_VERBOSE_4 -DQMX_WAIT_TRACING
set QCAMMEX_COMPILER_ARGS=%QCAMMEX_COMPILER_ARGS_NON_MEX% -DMATLAB_MEX_FILE

set QCAMMEX_QCAMSDK_INCLUDE_PATH=C:\Program Files\QImaging\QCam SDK\Headers
set QCAMMEX_INCLUDES=/I. /I%QCAMMEX_VS_HOME%\include /I"%QCAMMEX_MATLAB_PATH%\extern\include" /I"%QCAMMEX_QCAMSDK_INCLUDE_PATH%" /I"%QCAMMEX_MS_SDK%\Include" /I"%QCAMMEX_QCAPSDK_INCLUDE_PATH%"

set QCAMMEX_COMPILER_TARGET_PREFIX=/Fo
set QCAMMEX_LINKER_TARGET_PREFIX=/OUT:

set QCAMMEX_LINKER_ARGS_NON_MEX=/nologo /SUBSYSTEM:console
set QCAMMEX_LINKER_ARGS=%QCAMMEX_LINKER_ARGS_NON_MEX% /EXPORT:mexFunction /DLL

set QCAMMEX_MATLAB_LIB_PATH=%QCAMMEX_MATLAB_PATH%\extern\lib\win32\microsoft
set QCAMMEX_QCAM_LIB_PATH=C:\Program Files\QImaging\QCam SDK\Libs

set QCAMMEX_LINKER_LIBS="%QCAMMEX_MATLAB_LIB_PATH%\libmx.lib" "%QCAMMEX_MATLAB_LIB_PATH%\libmex.lib" "%QCAMMEX_MATLAB_LIB_PATH%\libmat.lib" "%QCAMMEX_MS_SDK%\lib\uuid.lib" "%QCAMMEX_VS_HOME%\lib\libcmt.lib" "%QCAMMEX_MS_SDK%\lib\kernel32.lib" "%QCAMMEX_MS_SDK%\lib\User32.lib" "%QCAMMEX_VS_HOME%\lib\oldnames.lib" "%QCAMMEX_MS_SDK%\lib\Advapi32.lib" "%QCAMMEX_QCAM_LIB_PATH%\QCamDriver.lib"

rem %QCAMMEX_CL_BIN%\dumpbin QCamDriver.dll /EXPORTS

:COMPILE_EXE
echo Compiling executable...
%QCAMMEX_COMPILER% %QCAMMEX_COMPILER_ARGS_NON_MEX% %QCAMMEX_INCLUDES% %QCAMMEX_COMPILER_TARGET_PREFIX%qcammex.obj qcammex.c

:LINK_EXE
echo Linking executable...
%QCAMMEX_LINKER% %QCAMMEX_LINKER_ARGS_NON_MEX% qcammex.obj %QCAMMEX_LINKER_LIBS% %QCAMMEX_LINKER_TARGET_PREFIX%qcammex.exe

:COMPILE_MEX
echo Compiling mex file...
%QCAMMEX_COMPILER% %QCAMMEX_COMPILER_ARGS% %QCAMMEX_INCLUDES% %QCAMMEX_COMPILER_TARGET_PREFIX%qcammex.obj qcammex.c

:LINK_MEX
echo Linking mex file...
%QCAMMEX_LINKER% %QCAMMEX_LINKER_ARGS% qcammex.obj %QCAMMEX_LINKER_LIBS% %QCAMMEX_LINKER_TARGET_PREFIX%qcammex.mexw32

:CLEAN
echo Cleaning...
del *.obj
del qcammex.exp
del qcammex.lib

:TEST
rem qcammex

goto EOF

:EOF